### ISSUE TITLE
Refactor project to use one name for this operator

### ISSUE THREAD

**Issue by jvoravong** [signalfx/splunk-otel-collector-operator#176]
Issue:
This project uses  splunk-otel-collector-operator and  splunk-otel-operator as the name of this operator in different places. We need to choose which name to move forward with and considerate all operator name values to the same value.

Pros for _splunk-otel-operator_:
- The Opentelemetry operator repo is named opentelemetry-otel-operator
- This repo will deploy instrumentation apps as well as the collector app

Pros for _splunk-otel-collector-operator_:
- Can't think of any at the moment.

Does anyone else have any input on this?

**Comment by aunshc** [comment]
Correct me if I am wrong, this is the upstream operator repository https://github.com/open-telemetry/opentelemetry-operator and it is named opentelemetry-operator. Since the operator is another mode of deployment other than the existing helm chart that is named splunk-otel-collector-chart and is based on the collector, I lean towards splunk-otel-collector-operator for consistency. Let me know what you think, thanks @jvoravong!

**Comment by jvoravong** [comment]
I'm okay with moving forward with splunk-otel-collector-operator as the name.
